version: 0.1

data_folder: 
  AOI: C:\\Users\\Anwender\\Desktop\\test_data\\SolarParks\\aoi_scenes.shp
  
satellite:
  Sentinel1:
    name: Sentinel1 
    processing_level: LEVEL3
    product_type: CARD-BS-MC 
  Sentinel2:
    name: Sentinel2
    processing_level: LEVEL3
    product_type: L3-WASP
  search_criteria:
    start_date: "2021-01-01T00:00:00Z"
    end_date: "2021-12-31T23:59:59Z"
    cloud_cover: 5
  
output_folder: ""