version: 0.1

shapefiles: 
  AOI: "/home/hoehn/data/input/aoi_scenes.shp"
  Solar: "/home/hoehn/data/input/SolarParks.shp"

model:
  Sentinel1+2: False

satellite:
  Sentinel1:
    name: Sentinel1 
    processing_level: LEVEL3
    product_type: CARD-BS-MC 
  Sentinel2:
    name: Sentinel2
    processing_level: LEVEL3
    product_type: L3-WASP
  search_criteria:
    start_date: "2021-05-01T00:00:00Z"
    end_date: "2021-07-31T23:59:59Z"
    cloud_cover: 5
  
output_folder: "/home/hoehn/data/output/"